### ISSUE TITLE
Support for g* and g#

### ISSUE THREAD

**Issue by bruno-** [bronson/vim-visual-star-search#3]
How about adding a support for these?
I've been in a few sitations where these could come handy. If nothing they should be added just for the sake of being consistent and feature complete..

**Comment by bronson** [comment]
Very true.  Don't think I'm ever going to find the time to make this change but I'll leave this open in case anyone else does.

**Comment by mboughaba** [comment]
> How about adding a support for these?
I've been in a few sitations where these could come handy. If nothing they should be added just for the sake of being consistent and feature complete..

g* or g# works out of the box. It expands the selection to the word under the cursor.
I am not sure what needs to be done here. I don't think it is a good idea to make g* expand beyond the word. If you want that behavior then visual select then * which is what this plugin is doing :1st_place_medal:

**Comment by bronson** [comment]
Thanks @mboughaba, that makes sense.  Closing for now.

If there's anything more that needs to be done then please comment here. I'm happy to reopen.

**Comment by kiryph** [comment]
see https://github.com/thinca/vim-visualstar for a different definition of `*` and `g*` in visual mode:

```
<Plug>(visualstar-*)			*<Plug>(visualstar-star)* *v_star*
			Search forward for the [count]'th occurrence of
			selection text in |Visual-mode| nearest to the cursor.
			If the character of head of selection text is
			'iskeyword' character, and outside of selection area
			is not 'iskeyword' character, "\<" is appended to the
			head of search word like same as |star|.
			The tail is also similar.

<Plug>(visualstar-g*)			*<Plug>(visualstar-gstar)* *v_gstar*
			Like |<Plug>(visualstar-star)|, but don't put "\<" and
			"\>" around the word.
```

If the visual selection are two ordinary words, e.g. `Hello World` in `blablabla Hello World blablabla`, pressing `*` performs the search `\<Hello World\>`.
If `g*` is pressed in the same situation, `Hello World` is the search query.
