### ISSUE TITLE
How about using <ctrl-g>* and <ctrl-g># for vimgrep searches?

### ISSUE THREAD

**Issue by bruno-** [bronson/vim-visual-star-search#4]
Apparently, `<leader>` [mappings in plugins are not cool anymore](http://vimcasts.org/blog/2014/02/follow-my-leader/).

How about changing those leader maps to use `<ctrl-g>` prefix? It even has a "grep" mnemonic..

**Comment by bronson** [comment]
Sorry for the delay, was making up my mind.  :)  Yeah, If I had it to do over again I'd do that.  At this point, this plugin is mature and stable...  I don't think the change would be worth it.  Closing, but thanks for the suggestion!
